### ISSUE TITLE
hemorragia intracraneal, subaracnoidea, neurocirugía...

### ISSUE THREAD

**Issue by arturogf** [arturogf/sodium-up#11]
1. Por un lado, se establece que tener h.i. actualiza la gravedad de la hiponatremia.
2. Por otro, en CSW se pregunta antecedentes de tener hemorragia subaracnoidea (un tipo de h.i.), neurocirugía, head injury...

¿Cómo lo modelamos todo? ¿Junto, separado?

**Comment by cuestamartin** [comment]
Poner "patología neuroquirúrgica cerebral: a) hemorragia intracraneal, b) hemorragia subaracnoidea, c) traumatismo craneoencefálico moderado/severo, d) hematoma subdural, e) otras, f) No."

**Comment by arturogf** [comment]
Metido. He puesto que por defecto se marque la opción "No", para mayor usabilidad. Cualquier otra que marque de las otras 5, será un argumento algo favor de CSW.
