### ISSUE TITLE
contradicción Gerontology-Guía en CSW

### ISSUE THREAD

**Issue by arturogf** [arturogf/sodium-up#12]
En el artículo de Gerontology pone que la UREA suele ser alta para diagnosticar CSW, y en la guía pone que: "The sodium resorptive defect has been attributed to a proximal tubular defect that is accompanied by increased uric acid and urea excretion, features that may make the use of BUN and uric acid levels unreliable for distinguishing between SIADH and CSW". 

El criterio de hipovolemia de la guía dice que el BUNN tiene que ser bajo (Urea).

**Comment by arturogf** [comment]
"Although not well studied, serum uric acid levels in CSW tend to be unexpectedly low"

del artículo de Trends in Endocrinology and Metabolism

**Comment by cuestamartin** [comment]
Efectivamente no discriminan perfectamente ambos cuadros. 

Yo lo modelaría de esta forma: 

Urea alta: muy en contra de SIADH, muy a favor de CSW
Urea normal: inespecífico, ambos
Urea baja: Apoya más SIADH, pero también puede verse en CSW ( asumiendo que el CSW es rarísimo), por lo que simplemente por incidencia de cada síndrome la mayoría serán SIADH y no CSW 

Con el ácido úrico creo que hay aún menos evidencia en este contexto.

**Comment by arturogf** [comment]
Vale, en SIADH tenemos la siguiente condición, hemos contemplado el BUN y la Creatinina altas, en conjunto:

(BUN > 20 AND (Creatinina_ser>1.1 AND Sexo="Mujer") OR (Creatinina_ser>1.3 AND Sexo="Hombre")) -> EN CONTRA

¿Las separo como dos argumentos? ¿o subirán y bajarán juntas?

**Comment by cuestamartin** [comment]
Cualquiera de los dos elevados va en contra. Los podemos separar. Un
SIADH tiene tanto la Creatinina como la Urea normales o bajas

**Comment by arturogf** [comment]
Ok gracias. Voy a poner el texto "BUN alto no sugiere euvolemia" (recuerda que comprobamos el BUN calculado) y por otro lado "Creatinina alta no sugiere euvolemia". Supongo que estos dos argumentos en contra se repite para todas las euvolémicas.

**Comment by cuestamartin** [comment]
Sí para todas

Perfecto

**Comment by cuestamartin** [comment]
Arturo,

¿Podrías mandarme el título de la presentación oral que diste ayer y
autores? Tengo que presentar mi CV este lunes actualizado para
intentar buscar fondos.

Muchas gracias,

Martín

**Comment by cuestamartin** [comment]
También intenta mandarme el algoritmo tmás actualizado.
Con el que me mandaste al meter un cirrótico descompensado me sale
hipovolémico, cuando tiene ascitis y edemas.

Tenemos que discutirlo. Mándame el link más actualizado que tengas de
la aplicación.

Muchas gracias

Martín

**Comment by arturogf** [comment]
Creo que cerramos este issue. Habría que comprobar los argumentos que hemos puesto sobre ácido úrico y BUN juntos, pero ya lo vamos viendo según validamos.
