### ISSUE TITLE
potasio bajo en contra de CSW?

### ISSUE THREAD

**Issue by arturogf** [arturogf/sodium-up#14]
TRENDS in Endocrinology and Metabolism Vol.14 No.4 May/June 2003

"In this regard, hypokalemia has not been a feature of CSW."

**Comment by cuestamartin** [comment]
Sí. 

Habitualmente tras la gran poliuria, estos pacientes presentan insuficiencia renal aguda ( no siempre), que puede condicionar incluso hiperpotasemia. Lo más normal, en los pocos casos reconocidos como verdaderos de CSW es que esté normal.

**Comment by arturogf** [comment]
Ok. Hecho
