### ISSUE TITLE
hematocrito y albumina para CSW?

### ISSUE THREAD

**Issue by arturogf** [arturogf/sodium-up#15]
increased hematocrit and increased serum albumin concentration -> CSW
normal hematocrit and normal serum albumin concentration -> SIADH

"TRENDS in Endocrinology and Metabolism Vol.14 No.4 May/June 2003" (TABLE 1)

**Comment by arturogf** [comment]
¿Serviría para diferenciar tb hipovolemia de euvolemia?

**Comment by cuestamartin** [comment]
No es necesario contemplar esos valores.
