### ISSUE TITLE
Recopilar en un link a un pdf los rangos/unidades de laboratorio utilizados

### ISSUE THREAD

**Issue by cuestamartin** [arturogf/sodium-up#18]
Ponerla al principio de la aplicación en una pantalla inicial de "Disclaimer" donde se incluya la información que se considere para el uso de la aplicación a nivel formativo.

**Comment by arturogf** [comment]
Done. He incluido el siguiente texto en la pantalla inicial de bienvenida a la herramienta.

![cap](https://cloud.githubusercontent.com/assets/729157/14848590/b63c0780-0c6e-11e6-8c3a-e5fa682e7c71.png)
