### ISSUE TITLE
añadir sepsis a favor de hipovolemia

### ISSUE THREAD

**Issue by arturogf** [arturogf/sodium-up#25]
Siempre que tenga criterios de hipovolemia, la sepsis ayuda a confirmar la hipovolemia. Si tras la validación de draft inicial ayudara, se considera meterlo.

**Comment by cuestamartin** [comment]
Quizás podemos no incluirlo para no complicar más. La presencia de sepsis apoya hipovolemia siempre y cuando el paciente no esté con sueros intravenosos. Es decir, si aparece en Urgencias y tiene 39 de fiebre, neumonía, no come en 3 días, urea elevada. Es un hipovolémico. 

Sin embargo si el mismo paciente recibe 3 litros intravenosos de suero y desarrolla la hiponatremia al 4º día de ingreso es mucho más probable que sea euvolémica y que de hecho le sobre volumen intravenoso. 

Por tanto quizás es liar más, que no aclarar.

**Comment by arturogf** [comment]
En principio lo descartamos para esta versión.
