### ISSUE TITLE
Calcular osmolalidad urinaria (OSM_ur) automáticamente

### ISSUE THREAD

**Issue by arturogf** [arturogf/sodium-up#4]
Preguntar a experto:

[(Na+ + K+) x 2] + (Urea/5.6) 

Así podemos quitar otra petición.

**Comment by arturogf** [comment]
Cuidado con la fórmula, porque es para osmolaRidad...adaptarla

**Comment by cuestamartin** [comment]
Hola Arturo, 

La osmolaridad urinaria debe ser de laboratorio. La plasmática sí que se puede calcular con un algoritmo que creo ya tenéis incorporado en el modelo. La urea en orina no se pide de rutina para el cálculo. Por otro lado la precisión del ensayo de laboratorio de la osmolaridad urinaria es muy alta. Se debe solicitar al laboratorio. No conozco ningún centro que no la mida directamente. Gracias

**Comment by arturogf** [comment]
Ok!
