### ISSUE TITLE
insuficiencia renal

### ISSUE THREAD

**Issue by mavalcarcel** [arturogf/sodium-up#47]
En la pregunta de insuficiencia renal habría que incluir insuficiencia renal crónica (no avanzada) y ver en que afecta ( ej. diagnóstico de SIADH)

**Comment by arturogf** [comment]
MªAngel: "En los casos en que a la pregunta de insuficiencia renal, incluye cualquier tipo insuficiencia, no hay que tener en cuenta los argumentos que evaluan la creatinin como alta." 

Es decir, hay que añadir a los criterio de creatinina alta:   AND (FuncionRenal  = "Normal")

**Comment by arturogf** [comment]
He metido el criterio en todos los que tienen creatinina alta, sea a favor o en contra.
