### ISSUE TITLE
referencia para hipoaldosteronismo

### ISSUE THREAD

**Issue by arturogf** [arturogf/sodium-up#50]
Aldosterone Deficiency and Resistance (Endotex, 2013)

http://www.endotext.org/wp-content/uploads/pdfs/aldosterone-deficiency-and-resistance.pdf

**Comment by arturogf** [comment]
Otra más (hay que ver dónde va cada una)

Etiology, diagnosis, and treatment of hypoaldosteronism (type 4 RTA)
William F Young, Jr, MD, MSc

**Comment by cuestamartin** [comment]
Tal como habíamos hablado lo mejor es poner las referencias (ambas) tras meter los valores de potasio en orina, osmolaridad en plasma y orina. Cuando aparezca la pantalla de hipoaldosteronismo como grupo sindrómico.

**Comment by arturogf** [comment]
Corregido.
