### ISSUE TITLE
peso de argumento ascitis/edemas en EAH

### ISSUE THREAD

**Issue by arturogf** [arturogf/sodium-up#53]
argument: -((1)),AscEd = "Yes"

Si presenta ascitis o edemas habría que poner (-10 o -50) ya que en ese contexto ya no puede ser euvolémica.

**Comment by arturogf** [comment]
Mirar #46

**Comment by cuestamartin** [comment]
La presencia de ascitis o edemas es un signo imposible en la hiponatremia euvolémica. Por lo tanto pondría -50

**Comment by arturogf** [comment]
De acuerdo. Pero el argumento ha cambiado a:

(AscEd="Yes") AND (FuncionRenal = "Normal") AND (InsufCardiaca  = "No" )
