### ISSUE TITLE
peso de argumento ascitis/edemas en hipotiroidismo

### ISSUE THREAD

**Issue by arturogf** [arturogf/sodium-up#54]
En el caso de hipotiroidismo, la presencia de edemas o ascitis no puede ser - 50

La razon es porque en el hipotiroidismo mixedematoso ( hipotiroidismo grave); se desarrolla un tipo de edemas ( que es duro, crónico y no deja fóvea a la exploración), distinto de pacientes en ICC o cirróticos. Por tanto, su presencia no descartar hipotiroidismo severo, al contrario es posible verlo pero con otras características. 
En este contexto lo más discriminador es : 

Bioquímica consistente con hipotiroidismo severo ( T4L muy baja y TSH muy elevada) +50
Bioquímica no consistente con lo anterior: -50

**Comment by arturogf** [comment]
Mirar #46

**Comment by cuestamartin** [comment]
Esta pregunta del hipotiroidismo ya está comentada, ¿verdad?

**Comment by arturogf** [comment]
Duplicado del #62
