### ISSUE TITLE
Peso de la TO en polidipsia primaria

### ISSUE THREAD

**Issue by cuestamartin** [arturogf/sodium-up#56]
El peso de TO baja es -20 para PP, Sin embargo, tener la TO en el resto de las hipovolemicas es +1. Creo que hay mucha diferencia en la relevancia del peso. 
Especialmente dado que la TO a veces es difícil de valorar, especialmente para quien no lo usa de manera habitual. Por tanto en caso de que sea baja yo propongo -5. 

Para el caso de Presion venosa yugular baja, sí que dejaría -20 puesto que es más fácil de medir de manera objetiva.

**Comment by arturogf** [comment]
de acuerdo.

**Comment by arturogf** [comment]
Corregido
