### ISSUE TITLE
Cambio de peso y de nombre

### ISSUE THREAD

**Issue by cuestamartin** [arturogf/sodium-up#57]
argument :: -((50.0)),ConsumoAgua="Bajo" OR ConsumoAgua="Normal"

Comentario: 
Quizás habría que añadir consumo de Agua/**Otros líquidos**
Pongo el ejemplo de un potómano de cerveza que vive en la calle. Suelen beber bastante ( cerveza), pero poca agua o a veces nula. Por tanto deberíamos cambiar el nombre para no dar lugar a confusión. 

De igual forma separaría los pesos: 

 -((50.0)),ConsumoAgua="Bajo"

-((5)) ConsumoAgua="Normal"   Muy imporbable que tengas PP si bebes una cantidad normal.de agua. Sin embargo 3 litros para una persona de 80 kg en Agosto puede ser normal, mientras que para un abuelo de 85 años con demencia, desnutrición etc es excesivo--> polidipsia. 
Por lo vago del punto de corte no penalizaría si ponen ingesta de agua normal tanto. Lo que es normal para un paciente puede no serlo para el siguiente para un mismo volumen de líquidos.

**Comment by arturogf** [comment]
de acuerdo con el peso menor de agua normal. 

Se puede añadir otros líquidos, pero serían no alcohol. Alcohol en exceso va en otra pregunta, y en nuestro diagnóstico la potomanía de cerveza está en  baja ingesta de solutos, ¿no?

**Comment by arturogf** [comment]
Corregido lo de dividir en dos argumentos.

**Comment by arturogf** [comment]
Poner como argumento de p.p.

AlcoholEnExceso=YES and ComePoco=YES a favor.

Añadir "otros líquidos"

Descripción: té, refrescos, etc.

**Comment by mavalcarcel** [comment]
Polidipisa primaria incluye alcohol en exceso a favor +1, pero solo si NOT come poco

**Comment by arturogf** [comment]
Revisado y corregido.
