### ISSUE TITLE
DietaHabito incluye Alcohol en exceso en polidipsia primaria

### ISSUE THREAD

**Issue by cuestamartin** [arturogf/sodium-up#58]
argument :: 1.0,DietaHabitos includes "Alcohol en exceso"            

De igual forma que lo tenemos metido para el diagnóstico de
candidate :: 'LowSoluteIntake' 
 creo que deberíamos meterlo para polidipsia primaria.

Esto es debido a que un porcentaje elevado de pacientes con Polidipsia Primaria son por exceso de ingesta de alcohol. 
De manera que solo contabilizara si incluye de manera + la ingesta de alcohol en exceso (+1)

**Comment by arturogf** [comment]
Curioso. En la guía no aparece así. Lo hablamos en la siguiente reunión y tomamos una decisión.

**Comment by arturogf** [comment]
Mirar #57
