### ISSUE TITLE
candidate :: 'euvolemicEAH' ;

### ISSUE THREAD

**Issue by cuestamartin** [arturogf/sodium-up#59]
candidate :: 'euvolemicEAH' ;

argument :: -((50)),Ortostatismo  = "Yes"                          

No lo penalizaría tanto, puesto que uno puede tener un SIADH y que le hayan pautado un exceso de medicación antihipertensiva o betabloqueante que se traduzcan en ortostatismo. Es poco frecuente, pero por eso ningun signo ni parametro de laboratorio tiene un valor predictivo o negativo del 100% para un diagnostico concreto. Por ello, para que no te descarte SIADH ( que sigue siendo la causa mas frecuente de hiponatremia en ingresados y ambulantes) solo en base a ese criterio, le daría como mucho -5. 
Es poco probable. Pero puedes tener un SIADH cronico `por ejemplo por bronquiectasias, y además tener hipotension ortostatica por tratamiento farmacologico , no porque estés hipovolemico.

**Comment by arturogf** [comment]
Vale. Te has equivocado al poner el título del problema y nos hemos liado. Ya hemos visto que ese argumento no está en EAH pero sí en SIADH. Ok.

**Comment by arturogf** [comment]
Corregido en SIADH, peso a -5.
