### ISSUE TITLE
¿Añadir insuficiencia renal como criterio a favor de polidipsia primaria?

### ISSUE THREAD

**Issue by arturogf** [arturogf/sodium-up#6]
Preguntar a Martín

**Comment by cuestamartin** [comment]
No al contrario. Ejemplo. Un alcoholico bebe 4 litros de cerveza ( que es muy hipotónica) , practicamente agua, lo que hace que se hemodiluya su sangre ( mucha agua), le baja el sodio, el potasio, la urea, la creatinina, el acido urico....
Por lo tanto lo normal es que los parámetros de función renal estén incluso bajos, no altos como en la insuficiencia renal. 
El unico caso sería un paciente que tuviera de base insuficiencia renal crónica avanzada y que bebiera  grandes cantidades de líquidos, es rarísimo, y en cualquier caso nunca llegaría a normalizar su creatinina. 

En otras palabras la función renal es normal. 

Dime si es suficientemente claro. 

Abrazo

Martín

**Comment by mavalcarcel** [comment]
Hola Martín, 
Esto te lo preguntamos porque se hace una pregunta en antecedentes de si tiene insuficiencia renal y lo que queríamos saber es si el paciente tiene insuficiencia renal previa tendría más facilidad de presentar polidipsia. Porque en la guía dice exactamente: "Excessive water intake itself is rarely of sufficient magnitude to produce hyponatremia in the presence of normal renal function". ¿esto tampoco entonces?

**Comment by arturogf** [comment]
No ponerlo.
