### ISSUE TITLE
para ADHfamily/SIADH

### ISSUE THREAD

**Issue by cuestamartin** [arturogf/sodium-up#60]
Este argumento está mal: 

argument :: 1.0,isknown(cortisol) AND (cortisol < 3) AND (glucocorticoids="No")             

Si tenemos un Cortisol matutino < 3 mcg/dl en ausencia de glucocorticoides es diagnóstico de insuficiencia suprarrenal ( luego habrá que ver si primaria o secundaria), no puede sumar+1

Por tanto propongo con los mismos argumentos poner -20, ya que por definición o tienes una insuficiencia suprarrenal central o SIADH. Luego en la evolucion les puedes tratar con corticoides y algunos tienen SIADH debajo, pero dicho esto, en el momento del diagnóstico con ese cortisol, no puedes diagnosticar a nadie de SIADH

**Comment by arturogf** [comment]
Ok, lo cambio  a -20. Muy bien detectado! :+1:

**Comment by arturogf** [comment]
Corregido
