### ISSUE TITLE
Explicación del siguiente argumento

### ISSUE THREAD

**Issue by cuestamartin** [arturogf/sodium-up#61]
Perdonar no entiendo el siguiente argumento: 
argument :: ln(Na_ur) - 2,(ConsumoAgua = "Normal" OR ConsumoAgua = "Alto") AND (ConsumoSal = "Normal" OR ConsumoSal = "Alto") AND diureticos="No" AND Na_ur > 20                                             

¿Es el logaritmo neperiano del Nau -2?

**Comment by arturogf** [comment]
Esto es una fórmula que me inventé para que sea adaptativo el peso respecto al valor del Na_ur (cuanto más alto es el na_ur más peso tiene el argumento, variando -el peso- si no recuerdo mal entre 1 y 2.8, pero lo podemos comprobar). Por eso sale el valor de peso con muchos decimales, porque no fui capaz de encontrar alguna forma de que presente menos decimales en el sistema.
