### ISSUE TITLE
euvolemica por hipotiroidismo

### ISSUE THREAD

**Issue by cuestamartin** [arturogf/sodium-up#62]
candidate :: 'euvolemicHypothyroidism' ;

argument :: -((50)),AscEd = "Yes"                                                         

Creo recordar que hablamos de que en hipotiroidismo grave, el que produce hiponatremia, los pacientes suelen terner mixedema, que es un tipo de edema de tejido celular subcutáneo que es duro, y no deja fóvea al presionar. 

Por tanto no te puede descartar hipotiroidismo la presencia de edemas, al contrario, te obliga a solicitarlo especialmente si son duros los edemas a la palpación. 

Lo que no se es que peso darle ni a favor ni en contra...lo podemos discutir

**Comment by arturogf** [comment]
Pues yo creo que le ponemos neutro y damos esa explicación que comentas: "los pacientes que presentan mixedema pueden tener edemas, por lo que no puede descartarse. Este tipo de edemas no dejan fóvea".

**Comment by arturogf** [comment]
Corregido
