### ISSUE TITLE
hiponatremia en paciente hepatópata

### ISSUE THREAD

**Issue by cuestamartin** [arturogf/sodium-up#63]
argument :: 1.0,hepatopatia="Yes"

Como en el paciente con cirrosis o hepatopatía crónica, la causa más frecuente es que sea hipervolémica por descompensacion hidrópica/cirrosis, quizás convendría darle un peso mayor positivo. ¿+3?

A discutir

**Comment by arturogf** [comment]
Pues no tengo ni idea. Como no hemos probado muchos casos de este tipo... pero lo podemos poner a +3 y ver cómo se comporta. Hay que tener en cuenta que otros argumentos de igual consideración en otras hiponatremias estamos poniendo +1... hay que pensar si lo importante es afinar esto para un mejor ranking o para confirmar/descartar. 

En principio, lo voy a hacer, y ya vemos.

**Comment by arturogf** [comment]
Corregido, a +3.0
