### ISSUE TITLE
candidate :: 'hipervolemicHF', Insuficiencia cardiaca

### ISSUE THREAD

**Issue by cuestamartin** [arturogf/sodium-up#64]
candidate :: 'hipervolemicHF' 

argument :: 1.0,DiuASA  = "Yes" AND InsufCardiaca  = "Yes"  

Si estás en insuficiencia cardiaca ( diagnostico clinico con combinacion de signos, sintomas y pruebas de imagen), y además estás con tratamiento diuretico para ello (tratamiento indicado una vez el diagnostico); casi con total seguridad el diagnostico es Insuficiencia cardiaca. Solo en el caso de que lleves varios dias con tratarmiento diuretico en exceso; te podrías plantear que has secado al paciente y que lo que tiene es una hiponatremia hipovolemica por diureticos. 

Por tanto, yo le daría un peso mayor +5 por ejemplo puesto que con mucho es lo más probable en ese contexto.

**Comment by cuestamartin** [comment]
Por ejemplo, en ese mismo diagnostico, no podemos dar el mismo peso a 

argument :: 1,TO  = "Normal" OR TO  = "Alto"                                             que a la combinacion de estar en insuficiencia cardiaca y ademas tener diureticos

¿No os parece?

**Comment by cuestamartin** [comment]
Otra opción que se me ocurre es: 

Si estás en Insuficiencia cardíaca (YES) +  presión venosa yugular elevada; eso solo puede ser insuficiencia cardica. 

Otra forma de ponerlo quizás sería ICC+Diureticos+PVY elevada ¿+5?

**Comment by arturogf** [comment]
Nos parece que podemos poner ese argumento en contra en la de diuréticos, es decir:

argument :: -5.0,DiuASA = "Yes" AND InsufCardiaca = "Yes"

Para la hipovolemicDiuretics. Ya que el objetivo de lo que tú propones es que no te diagnostique la otra. Mª Angel dice que si lo has secado ya no tendría tantos sintomas de IC ¿puede ser?

**Comment by arturogf** [comment]
Corregido. No he puesto nada aclaratorio en la descripción ¿qué queréis que ponga?

**Comment by arturogf** [comment]
descripción: "En el caso de que el paciente presente síntomas de insuficiencia cardíaca y toma diuréticos de asa, sería conveniente tratar primero la insuficiencia cardíaca y reevaluar"

**Comment by arturogf** [comment]
Revisado.
