### ISSUE TITLE
candidate :: 'hipovolemicGastro' ;

### ISSUE THREAD

**Issue by cuestamartin** [arturogf/sodium-up#65]
argument :: -((10.0)),NOT(Diarrea="Yes") AND NOT(Vomitos="Yes")                 

Le daría un peso de -20 al menos. En otras palabras, si no tienes ni vomitos ni diarrea no te puede salir como una opcion en ningun caso que sea por perdidas gastrointestinales. Por tanto, en este caso sí que debe descartarlo para que no salga dentro de las posibles opciones.

**Comment by arturogf** [comment]
Ok.

**Comment by arturogf** [comment]
Corregido.
