### ISSUE TITLE
diagnostico de hipoaldosteronismo

### ISSUE THREAD

**Issue by cuestamartin** [arturogf/sodium-up#66]
argument :: 11.0,(isknown(GTPo) AND GTPo>0 AND GTPo<4 AND Edad>18)

Aunque siempre he utilizado el punto de corte 4, ultimamente Isabelle usa 5, con los mismo exactos criterios. Imagino que depende de la sensibilidad que queramos poner para ese diagnostico. Es decir, si alguien tiene un gradiente de 4.7 por ejemplo, esta claramente hipovolemico, un Kp de 5.6 mmol/l, y además tiene una causa de hipoaldosteronismo ( ejempo tratamiento con espironolactona que bloquea el receptor mineralocorticoide ); en ese caso el diagnostico mas probable con mucho es hipoaldosteronismo.Como ahora está usando ese punto de corte (5 para el GTP), y hasta donde yo se no existe evidencia alguna para la superioridad de uno sobre otro, si no es mucho follon cambiar todos los argumentos para un punto de corte de 5 estaría bien hacerlo.

**Comment by arturogf** [comment]
Me parece mejor 5, ya que no afecta a descartar otros diagnósticos. Así diagnosticará más veces hipoaldosteronismo como probable... otra cosa ya será el peso ese de 11... que lo puede colocar el primero con facilidad. No se si ponerlo +5 (si te has dado cuenta, los valores altos los hemos puesto en todo caso para descartar, no para aupar a un diagnóstico al primer lugar con "facilidad")...

**Comment by arturogf** [comment]
En principio subo el punto de corte y bajo el peso a +5.
