### ISSUE TITLE
general de criterios hipovolémicos  y pesos

### ISSUE THREAD

**Issue by mavalcarcel** [arturogf/sodium-up#67]
- Los argumentos de hipovolemia van por separado a veces y juntos otras.  Creo que podría tener sentido ponerlos por separado a favor su presencia (cada uno independiente) y juntos (la ausencia de todos) en contra cuando sea hipovolémica (salvo las excepciones), y al revés si es euvolémica/hipervolémica. Juntos su ausencia a favor e independientes en contra. Valoradlo. En dos grupos: exploración física y analítica. 
- Por otro lado los pesos varían,  no estoy segura si por criterio clínico ¿la PV alto es -10 para hipovolémicas y -20 para euvolémicas?
- Por otro lado un peso negativo de -10 descartará muchas veces un diagnóstico, ¿realmente queremos darle un peso tan alto este único signo? 
- Por otro lado, como argumentos en contra se está dando más peso a los criterios de exploración física, pero quizá tienen más peso los analíticos, ¿o no? ¿son más sensibles y específicos o solo más sensibles?

**Comment by cuestamartin** [comment]
Por otro lado los pesos varían, no estoy segura si por criterio clínico ¿la PV alto es -10 para hipovolémicas y -20 para euvolémicas?

## Respuesta: no , debería ser el mismo para ambas. Es un error. 

Por otro lado un peso negativo de -10 descartará muchas veces un diagnóstico, ¿realmente queremos darle un peso tan alto este único signo?

candidate :: 'euvolemicADHFamily' ;
argument :: 1,OSM_p  < 275  
argument :: -((50)),Ortostatismo  = "Yes"                                                            

Aquí al ortostatismo le daría -10, no -50. Y solo en SIADH. Recordando que los pacientes con insuficiencia suprarrenal central si pueden tener ortostatismo por el deficit de cortisol que en sí mismo aumenta el tono vascular, y su disminucion produce ortostatismo. 

En relación al peso de -10 o incluso menor, lo fuimos dando sobre la marcha en base a la relevancia clínica que considerabamos. Entiendo que quizás sería mejor homogeneizar pero creo que la aplicación va a serguir acertando igualmente. Cuando poníamos -50 claramente es porque lo descarta. 
El peso de -10 o -20 es más subjetivo, pero en general queremos que lo descarte. 

## Dicho esto, a todo aquello que es subjetivo, ejemplo edemas, PVY etc, como es subjetivo y está sujeto a errores de medida por el médico, quizás no tiene sentido darles -20 ( ejemplo en PV), porque efectivamente lo va a descartar y puede ser un error de la explorqación física. Podíamos darle -5 a todos los hallazgos físicos de la exploracion fisica que son subjetivos ( edemas, PV, TO).

Por otro lado, como argumentos en contra se está dando más peso a los criterios de exploración física, pero quizá tienen más peso los analíticos, ¿o no? ¿son más sensibles y específicos o solo más sensibles?
Sí, efectivamente son más precisos desde el punto de vista diagnóstico los analíticos, menos sujetos a errores. Por ello quizás la exploración fisica debemos de disminuir los pesos ( los que tengan -10 o -20, ponerlo como -5?)

---

Los argumentos de hipovolemia van por separado a veces y juntos otras. Creo que podría tener sentido ponerlos por separado a favor su presencia (cada uno independiente) y juntos (la ausencia de todos) en contra cuando sea hipovolémica (salvo las excepciones), y al revés si es euvolémica/hipervolémica. Juntos su ausencia a favor e independientes en contra. Valoradlo. En dos grupos: exploración física y analítica.

Respuesta: aquí Maria Ángeles estoy más perdido que un pulpo en un garaje. Entiendo la idea, pero no el trasfondo de que sea distinto en uno u otro diagnostico. Si ambos estáis de acuerdo adelante. Es un tema de que el cerebro no me da más!!

**Comment by arturogf** [comment]
He cambiado el peso de "PV=Baja" en euvolémicas de -20 a -10.

Quedar por mirar si cambiamos todo a -5.

**Comment by arturogf** [comment]
Lo cambiamos a -5, salvo AscitisEdemas que mantenemos -10.
