### ISSUE TITLE
candidate :: 'SodioNormal'  duda Arturo

### ISSUE THREAD

**Issue by mavalcarcel** [arturogf/sodium-up#68]
Estos son los argumentos que se muestran

argument :: for,MedSodio = "Indirecta" AND (Nacor >=135) AND (Nacor <=145)  
  argument :: for,MedSodio = "Directa" AND (Na_pl >= 135) AND (Na_pl <= 145)      

FALTA SODIO MAYOR DE 145 NO??? En algún momento estaba, me suena. Y poner hipernatremia y que no aplica está guía o lo que sea no??? Igual no era aquí

**Comment by arturogf** [comment]
Vale, lo he puesto.
