### ISSUE TITLE
Polidipsia primaria y baja ingesta de solutos

### ISSUE THREAD

**Issue by mavalcarcel** [arturogf/sodium-up#69]
Argumento OSM_ur >100 tiene -10  para polidipsia y -1 para baja ingesta de solutos.  entiendo que en polidispisa tiene mucho peso  (habría que añadir y función renal normal????) pero en la guía en baja ingesta de solutos pone también que la osmolaridad en orina es típicamente baja. La pregunta es ¿es tanta la diferencia del peso entre las dos?

**Comment by cuestamartin** [comment]
Sí. En polidipsia primaria prácticamente siempre es menor de 100 ( digo prácticamente siempre porque hay que esperar a inhibir la vasopresina para empezar a mear puro agua con OsmU<100). Si la orina recogida es de antes de inhibir completamente la vasopresina ( vida media de 20 minutos), puedes tener OsmU bajas cercanas a 100 ( Ej 150 mOsm/Kg), pero si cada media hora recogieramos orina, encontrariamos la que tiene <100 mOsm/Kg

En cambio en baja ingesta de solutos, sí es más frecuente encontrarla entre 100-200 mOsm/kg de ahí el menor peso. En baja ingesta de solutos, la osmU está relativamente baja porque no se excreta urea ni sodio, pero la vasopresina no está siempre totalmente inhibida, sobre todo en los casos que coexiste con baja ingesta de agua ( anorexia, cancer) donde se eleva para mantener la volemia.
