### ISSUE TITLE
Por ejercicio tres puntos

### ISSUE THREAD

**Issue by mavalcarcel** [arturogf/sodium-up#71]
como la anterior. aunque está clasificada como euvolémica puede ser hipovolémica y por eso los argumentos de hipovolemia no van ni favor ni en contra. ¿¿¿¿ y los de analítica, porque hay dos en contra???

argument :: -((50)),(AscEd="Yes") AND (FuncionRenal = "Normal") AND (InsufCardiaca  = "No" ) . En todas las demás, los edemas y ascitis es menos 10, ¿tiene mucho más peso en contra en esta tener edemas realmente?

mujeres y aines factor de riesgo. ¿añadimos mujer como un punto a favor??

**Comment by cuestamartin** [comment]
Si la guía dice lo de ser mujer es factor de riesgo, sí añadirlo. Personalmente lo desconocía. En el fondo es un cuadro raro, y que se ve tras maratones, y sin ser sexistas, no sé si hay más mujeres que hombres en los maratones...jaja. Era broma. 

Sí tiene sentido que tengan más riesgo de hacer clínica severa en este contexto, igual que en la hiponatremia aguda por menor espacio dentro del encéfalo, menos volumen dentro de la calota, mayor riesgo de herniacion cerebral. 

Edemas solo se vería en este contexto si el paciente entra en insuficiencia cardiaca aguda o existe otra patologia coincidente. Dicho esto, yo pondría -10 para homogeneizar, puesto que no tiene mas peso en este cuadro que en el resto de euvolémicas.

**Comment by arturogf** [comment]
Cambiado a -10.

Añadido lo de ser mujer con +1.
