### ISSUE TITLE
SIADH duda Arturo

### ISSUE THREAD

**Issue by mavalcarcel** [arturogf/sodium-up#72]
ln(Na_ur) - 2,(ConsumoAgua = "Normal" OR ConsumoAgua = "Alto") AND (ConsumoSal = "Normal" OR ConsumoSal = "Alto") AND diureticos="No" AND Na_ur > 20            

Creo que en la función adaptativa no hace falta meter el consumo de agua en realidad  porque si te sale está bien, da igual el agua que beba.

**Comment by arturogf** [comment]
Ok, le quito lo del agua.
