### ISSUE TITLE
duda SIADH

### ISSUE THREAD

**Issue by mavalcarcel** [arturogf/sodium-up#73]
argument :: -((50)),FuncionRenal  = "Insuficiencia renal aguda"     

¿la insuficiencia renal crónica que tampoco tiene función renal normal no iría en contra de SIADH?

**Comment by cuestamartin** [comment]
Sí exactamente igual. Por definición así es. Así que podemos incluir el mismo peso. 

Dicho esto, esto es algo que en el futuro cambiará. Porque un paciente puede tener ambas cosas. Ejemplo, tener insuficiencia renal crónica por diabetes, y desarrollar una secreción marcada de ADH por tener un cancer microcitico de pulmon. Siendo estrictos y basados en la definicion de SIADH, este paciente del ejemplo no tiene SIADH, por tener insuficiencia renal cronica. Sin embargo en su hiponatremia la causa es la secrecion persistente por el tumor, y por tanto un SIADH , aunque por definición no lo tiene, basado en los criterios clásicos de Janicic y Verbalis. Eso cambiará en el futuro. Pero de momento, va en contra. Espero no haberos liado.

**Comment by arturogf** [comment]
Ok, añadida la crónica.
