### ISSUE TITLE
argumentos deficiencia glucocorticoides Comprobar

### ISSUE THREAD

**Issue by mavalcarcel** [arturogf/sodium-up#74]
argument :: -((50)),diureticos="Yes"  
  argument :: -((50.0)),Hipotiroidismo="Yes"  
  argument :: -((1.0)),(ConsumoSal = "Bajo") AND Na_ur < 20  
  argument :: 1,FuncionRenal  = "Normal" AND diureticos="No"  
  argument :: ln(Na_ur) - 2,(ConsumoAgua = "Normal" OR ConsumoAgua = "Alto") AND (ConsumoSal = "Normal" OR ConsumoSal = "Alto") AND diureticos="No" AND Na_ur > 20  
  argument :: -((1.0)),NOT(OSM_ur > 100)  AND FuncionRenal="Normal" AND OSM_p < 280                                                           

¿Estos argumentos son así para deficiencia de glucocorticoides? Es que me parecen de SIADH, no sé si todos aplican también aquí.  ¿la función del Na en orina es también adaptativa para deficiencia de glucocorticoides? ¿Diuréiticos e hipotirodismo son argumentos en contra?

**Comment by cuestamartin** [comment]
Todos aplicarían aquí. De hecho la insuficiencia suprarrenal central es exactamente igual al SIADH, salvo que la causa del SIADH en sí mismo es el déficit de cortisol. Dicho de otra manera, se produce un SIADH por déficit de cortisol, pero no se llama SIADH sino hiponatremia por insuficiencia suprarrenal central. 

Cualquier causa con diuréticos queda falseada. Por tanto , si el paciente toma diuréticos es muy difícil saber si existe otra causa hasta que se suspendan los diuréticos. 

Hipotiroidismo severo no iría en contra en este caso. La razón es que si la causa es por una fallo en la hipófisis ( ejemplo un tumor hipofisario grande), esto te produce tanto hipotiroidismo severo como insuficiencia suprarrenal central teniendo en ese caso ambas causas como hiponatremia euvolémica, es decir, coinciden. Sin embargo siempre hay que tratar primero el déficit de ACTH primero con corticoides, antes que con hormona tiroidea. Por tanto, no iría en contra. El resto todos son válidos.

**Comment by arturogf** [comment]
Añadimos a la descripción de tomar diuréticos:

" si el paciente toma diuréticos es muy difícil saber si existe otra causa hasta que se suspendan los diuréticos."

Quitamos el arg. en contra para hipotiroidismo.
