### ISSUE TITLE
hipervolemia cirrosis duda

### ISSUE THREAD

**Issue by mavalcarcel** [arturogf/sodium-up#75]
candidate :: 'hipervolemiaCirrosis' ;
  argument :: 1.0,PV  = "Alto"  
  argument :: -((1.0)),PV="Normal" OR PV="Bajo" 

En todas prácticamente la PV alta es en contra -10 o -20, ¿aquí solo -1 no tener la pv alta?

**Comment by cuestamartin** [comment]
Creo que este punto tenemos que cambiarlo. Lo he estado revisando ya que en la guía no dice nada al respecto. En la cirrosis descompensada con edemas, la PVY puede estar baja, normal o alta. Me explico: 
1. Normalmente el exceso de volumen está en el abdomen y en el territorio esplácnico abdominal, lo que da a un aumento de presión a nivel de los capilares y se produce la salida de líquido al volumen intersticial. Causando edemas. Por otro lado, existe activación neurohumoral por baja presión sobre los barorreceptores que lleva a secretar ADH y se produce hiponatremia. 

Lo más frecuente es que la PVY sea normal o baja, porque hay hipertension portal en el hígado y la sangre no vuelve de manera adecuada al corazón , es decir menor presión en la vena cava inferior y superior, porque el volúmen está secuestrado en el abdomen. 

Dicho esto, las activaciones neurohumorales retienene sal, y agua, y pueden asociar insuficiencia cardiaca derecha, con aumento de PVY. 

Por tanto, lo más frecuente es que esté normal o baja, aunque puede derivar en insuficiencia cardiaca derecha y por tanto con PVY aumentada

Le daría un peso neutro (=) a todas ellas.

**Comment by arturogf** [comment]
Lo sintetizamos en 1 argumento:

PV="Baja" OR PV="Normal" OR PV="Bajo"  
Caption: Lo más frecuente es que la presión venosa sea normal o baja. Si evoluciona con IC derecha podría ser alta.
